# config/packages/twig.yaml
twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        current_user: '@App\Twig\GlobalVariables'


when@test:
    twig:
        strict_variables: true
