# config/services.yaml
services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Kernel.php'

    # Registro da extensão Twig
    App\Twig\StylosExtension:
        arguments: ['@security.helper']
        tags: ['twig.extension']

    # Registro do serviço de variáveis globais
    App\Twig\GlobalVariables:
        arguments: ['@security.helper']
